title:            scribble-cn
# Site description showing in site meta data, leave empty if unwanted.
description:      scribble-cn, a Jekyll theme
# Site url, without a slash at the end. By default, it is domain hosted your website.
url:              
signoff:          # Your name for signoff. Leave empty if unwanted.
disqus_shortname: # Shortname of disqus for comments in post. You can only set one between disqus_shortname and duoshuo id or leave empty if unwanted.
duoshuo_id:       # ID of duoshuo for comments in post. You can only set one between disqus_shortname and duoshuo id or leave empty if unwanted.
facebook_appid:   # Appid for like button. Leave empty if unwanted.
google_analytics: # Account if google_analytics. Leave empty if unwanted.

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/jxltom
    external:     true
permalink:        pretty

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
